export default {
  User: {
    type: 'object',

    properties: {
      id: {
        type: 'string',
        description: 'The auto-generated PK id'
      },
      userId: {
        type: 'string',
        description: "Well formated and autogenerated users'id (StaffId, StudentID, lectureID)"
      },
      firstname: {
        type: 'string',
        description: "User's first name"
      },
      lastname: {
        type: 'string',
        description: "User's last name"
      },
      email: {
        type: 'string',
        description: "User's email"
      },
      password: {
        type: 'string',
        description: "User's password (autogenerated)"
      },
      isInviteAccepted: {
        type: 'boolean',
        default: false,
        description:
          'Is user (admin or Lecture) invite link (after being created by admin) accepted ?'
      },
      role: {
        default: 'STUDENT',
        type: 'string',
        enum: ['STUDENT', 'LECTURER', 'ADMIN'],
        description: 'User role'
      }
    }
  },
  Token: {
    properties: {
      id: {
        type: 'number',
        description: 'The auto-generated PK id'
      },
      token: {
        type: 'string',
        enum: ['ACCESS', 'REFRESH', 'ACTVATION'],
        description: 'Token type'
      },
      type: {
        type: 'string',
        description: 'JWT tokens'
      },
      expires: {
        type: 'dateTime',
        description: 'Token expiration time'
      },
      blacklisted: {
        type: 'boolean',
        description: 'Is Tocken active'
      },
      userId: {
        type: 'number',
        descriotion: 'user formated and usable ID (StaffID , StudentID or )'
      }
    }
  }
};
