FROM node:18-bullseye

WORKDIR /app

EXPOSE 5000

COPY package.json package-lock.json ./
COPY .env .env

RUN npm pkg delete scripts.postinstall

COPY prisma/ ./prisma

RUN npm install

RUN npm run prisma:generate

COPY . .

RUN npm run test
