version: '3.0'
services:
  git-inspired-backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: git-inspired-backend
    restart: on-failure
    ports:
      - '3001:5000'
    env_file:
      - ../git-inspired-capstone-bn/.env
